spring:
  jersey:
    servlet:
      load-on-startup: 1

  datasource:
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      platform: postgres

  profiles:
    default: dev
